In [13]:
import numpy as np
import pandas as pd
import xarray as xr
from itertools import product

In [14]:
# Load probability table (trained on data <= 2024)
final_path='../data/processed/SPY_cond_ex_tab.nc'
ds = xr.open_dataset(final_path, engine='netcdf4')

# Load full price data
df = pd.read_csv(
    '../data/raw/SPY_daily_yahoo_raw.csv',
    skiprows=[0,1,2],
    header=None,
    names=['Date','Adj Close','Close','High','Low','Open','Volume'],
    index_col=0,
    parse_dates=True
)

df = df.sort_index()
prices = df['Adj Close']

In [15]:
prices_2025 = prices.loc['2025-01-01':'2025-12-31']

In [16]:
directions = ["+", "-"]
q_grid = ds.q.values
r_grid = ds.r.values
q_vals = [q for q in q_grid if 0.8 <= q <= 0.98 and abs(q*10 - round(q*10)) < 1e-8]
r_vals = [r for r in r_grid if r in (0.8, 0.85, 0.9, 0.95)]
taus = [100, 200, 300]
p_mins = [0.5]
se_maxes = [0.01]

In [17]:
quantile_thresholds = {}

# IMPORTANT: thresholds must be estimated using ONLY data available before the
# 2025 evaluation window, exactly mirroring the train/test split used to build
# the probability table in 02_baseline.ipynb (df[df.index <= '2024-12-31']).
# The previous version of this cell used `prices.values` (the FULL series,
# including all of 2025), which leaked test-period data into the entry-signal
# threshold even though the conditional-probability lookup itself was correctly
# trained on pre-2025 data only. That leak is fixed here.

prices_train = prices.loc[:'2024-12-31']
P = prices_train.values

for tau in taus:
    inc = P[tau:] - P[:-tau]
    for q in q_vals:
        quantile_thresholds[(tau, q, "+")] = np.quantile(inc, q)
        quantile_thresholds[(tau, q, "-")] = np.quantile(inc, 1 - q)

In [18]:
# --- Sanity check: confirm no 2025 data leaked into the threshold calculation ---
assert prices_train.index.max() <= pd.Timestamp('2024-12-31'), (
    "Leak check failed: prices_train extends past 2024-12-31"
)
print(f"Threshold training data ends: {prices_train.index.max().date()}")
print(f"Evaluation window starts:     {prices_2025.index.min().date()}")
print("OK: thresholds are computed strictly before the evaluation window.")

Threshold training data ends: 2024-12-31
Evaluation window starts:     2025-01-02
OK: thresholds are computed strictly before the evaluation window.

In [19]:
results = []
trade_logs = {}  # (q, r, tau) -> list of per-trade dicts, for auditing

price_array = prices.values
date_index = prices.index

for q, r, tau, p_min, se_max in product(
    q_vals, r_vals, taus, p_mins, se_maxes
):

    # --- lookup probability & uncertainty (PLUS ONLY) ---
    p_hat = ds.prob.sel(direction="+", tau=tau, q=q, r=r).item()
    p_se  = ds.prob_se.sel(direction="+", tau=tau, q=q, r=r).item()

    # --- eligibility ---
    if np.isnan(p_hat) or p_hat < p_min or p_se > se_max:
        results.append({
            "q": q,
            "r": r,
            "tau": tau,
            "p_min": p_min,
            "se_max": se_max,
            "trades": 0,
            "total_return_pct": 0.0,
            "mean_trade_return_pct": np.nan,
            "std_trade_return_pct": np.nan,
            "sharpe": np.nan
        })
        continue

    trade_pnls = []
    trade_rets = []   # per-trade simple return, normalized by EACH trade's own entry price
    trade_detail = []  # full audit record per trade

    # --- loop over all days ---
    for date in prices_2025.index:

        idx = date_index.get_loc(date)

        if idx - tau < 0 or idx + tau >= len(price_array):
            continue

        # --- signal: tau-day trailing increment as of `date` ---
        inc_now = price_array[idx] - price_array[idx - tau]
        thresh = quantile_thresholds[(tau, q, "+")]

        if inc_now < thresh:
            continue

        # --- trade P&L ---
        entry_price = price_array[idx]
        exit_price  = price_array[idx + tau]
        exit_date   = date_index[idx + tau]

        pnl = exit_price - entry_price
        trade_pnls.append(pnl)

        r_trade = pnl / entry_price   # simple per-trade return, own entry price as base
        trade_rets.append(r_trade)

        trade_detail.append({
            "entry_date": date, "exit_date": exit_date,
            "entry_price": entry_price, "exit_price": exit_price,
            "pnl": pnl, "trade_return": r_trade
        })

    trade_logs[(q, r, tau)] = trade_detail

    # --- compute portfolio-level return and Sharpe from per-trade returns ---
    if len(trade_pnls) == 0:
        total_return_pct = 0.0
        mean_r = np.nan
        std_r = np.nan
        sharpe = np.nan
    else:
        trade_returns = np.array(trade_rets)

        # Aggregate return: SUM of per-trade simple returns (each trade sized at
        # 1 unit of capital, no shared/constrained capital pool, no compounding
        # across trades -- this matches the "1 unit invested per trade" assumption
        # stated in the paper and is the same convention used in the original code).
        total_return_pct = 100 * trade_returns.sum()
        mean_r = trade_returns.mean()
        std_r = trade_returns.std(ddof=1)

        # Sharpe: mean/std of per-trade returns, scaled by sqrt(252/tau) to express
        # an "annualized" ratio under the convention that a non-overlapping investor
        # could deploy capital into one such tau-day trade roughly 252/tau times per
        # year. Trades ARE allowed to overlap in this strategy (multiple simultaneous
        # tau-day holding periods is a deliberate design choice, not a bug), so this
        # Sharpe should be read as a per-trade risk-adjusted return statistic scaled
        # to an annual basis, NOT as a claim about portfolio-level Sharpe under a
        # single, fully-invested capital constraint. See the Methodology section of
        # the paper for the explicit formula and its interpretation.
        if std_r > 0:
            sharpe = (mean_r / std_r) * np.sqrt(252 / tau)
        else:
            sharpe = np.nan

    results.append({
        "q": q,
        "r": r,
        "tau": tau,
        "p_min": p_min,
        "se_max": se_max,
        "trades": len(trade_pnls),
        "total_return_pct": total_return_pct,
        "mean_trade_return_pct": 100 * mean_r if len(trade_pnls) else np.nan,
        "std_trade_return_pct": 100 * std_r if len(trade_pnls) else np.nan,
        "sharpe": sharpe
    })

In [20]:
results_df = pd.DataFrame(results)

In [21]:
# --- DIAGNOSTIC: inspect raw per-trade records for one config to verify the
# return/Sharpe calculation by hand, rather than trusting only the aggregated
# results_df. Change the key below to inspect a different (q, r, tau) config.

inspect_key = (0.8, 0.8, 200)
detail_df = pd.DataFrame(trade_logs[inspect_key])

print(f"Config q={inspect_key[0]}, r={inspect_key[1]}, tau={inspect_key[2]}")
print(f"Number of trades: {len(detail_df)}")
print()
print(detail_df.head(10).to_string(index=False))
print("...")
print()
print(f"entry_price range: [{detail_df['entry_price'].min():.2f}, {detail_df['entry_price'].max():.2f}]")
print(f"trade_return range: [{detail_df['trade_return'].min():.4f}, {detail_df['trade_return'].max():.4f}]")
print(f"Sum of trade_return (-> total_return_pct/100): {detail_df['trade_return'].sum():.4f}")
print(f"Mean trade_return: {detail_df['trade_return'].mean():.4f}")
print(f"Std trade_return (ddof=1): {detail_df['trade_return'].std(ddof=1):.4f}")

# Manual recomputation of Sharpe from the raw detail table, fully independent of
# the aggregation logic above -- if this doesn't match results_df, something in
# the main loop is wrong.
tau_check = inspect_key[2]
manual_sharpe = (detail_df['trade_return'].mean() / detail_df['trade_return'].std(ddof=1)) * np.sqrt(252 / tau_check)
print(f"Manually recomputed Sharpe: {manual_sharpe:.4f}")
print()
print("Cross-check against results_df row for the same config:")
display(results_df[(results_df.q==inspect_key[0]) & (results_df.r==inspect_key[1]) & (results_df.tau==inspect_key[2])])

Config q=0.8, r=0.8, tau=200
Number of trades: 117

entry_date  exit_date  entry_price  exit_price        pnl  trade_return
2025-01-02 2025-10-21   576.280334  667.489258  91.208923      0.158272
2025-01-03 2025-10-22   583.485779  664.019104  80.533325      0.138021
2025-01-06 2025-10-23   586.847046  667.956665  81.109619      0.138213
2025-01-07 2025-10-24   580.213257  673.415588  93.202332      0.160635
2025-01-08 2025-10-27   581.060974  681.360352 100.299377      0.172614
2025-01-10 2025-10-28   572.189636  683.170044 110.980408      0.193957
2025-01-13 2025-10-29   573.076843  683.498169 110.421326      0.192682
2025-01-14 2025-10-30   573.865356  675.980957 102.115601      0.177943
2025-01-15 2025-10-31   584.303955  678.198364  93.894409      0.160694
2025-01-16 2025-11-03   583.180237  679.471130  96.290894      0.165113
...

entry_price range: [543.54, 631.74]
trade_return range: [0.0629, 0.2621]
Sum of trade_return (-> total_return_pct/100): 18.5778
Mean trade_return: 0.1588
Std trade_return (ddof=1): 0.0425
Manually recomputed Sharpe: 4.1925

Cross-check against results_df row for the same config:

,q,r,tau,p_min,se_max,trades,total_return_pct,mean_trade_return_pct,std_trade_return_pct,sharpe
1,0.8,0.8,200,0.5,0.01,117,1857.783131,15.878488,4.251248,4.192548

In [22]:
# --- FULL TRADING LOG: every individual trade, for every config, with a final
# reconciliation against results_df to verify total_return_pct and sharpe tally
# exactly with what the aggregated table reports. ---

log_rows = []

for (q, r, tau), detail in trade_logs.items():
    for i, trade in enumerate(detail, start=1):
        log_rows.append({
            "q": q,
            "r": r,
            "tau": tau,
            "trade_no": i,
            "entry_date": trade["entry_date"],
            "exit_date": trade["exit_date"],
            "invested": trade["entry_price"],   # 1 unit of capital invested at entry_price
            "exit_value": trade["exit_price"],
            "pnl": trade["pnl"],
            "trade_return_pct": 100 * trade["trade_return"],
        })

trade_log_df = pd.DataFrame(log_rows)
trade_log_df = trade_log_df.sort_values(["q", "r", "tau", "entry_date"]).reset_index(drop=True)

print(f"Total logged trades across all configs: {len(trade_log_df)}")
print()
print(trade_log_df.head(15).to_string(index=False))
print("...")
print()
print(trade_log_df.tail(10).to_string(index=False))

Total logged trades across all configs: 372

  q   r  tau  trade_no entry_date  exit_date   invested  exit_value        pnl  trade_return_pct
0.8 0.8  200         1 2025-01-02 2025-10-21 576.280334  667.489258  91.208923         15.827180
0.8 0.8  200         2 2025-01-03 2025-10-22 583.485779  664.019104  80.533325         13.802106
0.8 0.8  200         3 2025-01-06 2025-10-23 586.847046  667.956665  81.109619         13.821254
0.8 0.8  200         4 2025-01-07 2025-10-24 580.213257  673.415588  93.202332         16.063461
0.8 0.8  200         5 2025-01-08 2025-10-27 581.060974  681.360352 100.299377         17.261420
0.8 0.8  200         6 2025-01-10 2025-10-28 572.189636  683.170044 110.980408         19.395739
0.8 0.8  200         7 2025-01-13 2025-10-29 573.076843  683.498169 110.421326         19.268153
0.8 0.8  200         8 2025-01-14 2025-10-30 573.865356  675.980957 102.115601         17.794348
0.8 0.8  200         9 2025-01-15 2025-10-31 584.303955  678.198364  93.894409         16.069446
0.8 0.8  200        10 2025-01-16 2025-11-03 583.180237  679.471130  96.290894         16.511344
0.8 0.8  200        11 2025-01-17 2025-11-04 589.035339  671.416992  82.381653         13.985859
0.8 0.8  200        12 2025-01-21 2025-11-05 594.427124  673.743713  79.316589         13.343366
0.8 0.8  200        13 2025-01-22 2025-11-06 597.768616  666.514893  68.746277         11.500483
0.8 0.8  200        14 2025-01-23 2025-11-07 601.031250  667.171082  66.139832         11.004391
0.8 0.8  200        15 2025-01-24 2025-11-10 599.276672  677.581909  78.305237         13.066625
...

  q   r  tau  trade_no entry_date  exit_date   invested  exit_value        pnl  trade_return_pct
0.9 0.8  200        99 2025-07-17 2026-05-04 622.757629  718.010010  95.252380         15.295257
0.9 0.8  200       100 2025-07-18 2026-05-05 622.301514  723.770020 101.468506         16.305361
0.9 0.8  200       101 2025-07-21 2026-05-06 623.481506  733.830017 110.348511         17.698762
0.9 0.8  200       102 2025-07-22 2026-05-07 623.570740  731.580017 108.009277         17.321095
0.9 0.8  200       103 2025-07-23 2026-05-08 628.875793  737.619995 108.744202         17.291841
0.9 0.8  200       104 2025-07-24 2026-05-11 629.083984  739.299988 110.216003         17.520078
0.9 0.8  200       105 2025-07-25 2026-05-12 631.741455  738.179993 106.438538         16.848433
0.9 0.8  200       106 2025-07-28 2026-05-13 631.582825  742.309998 110.727173         17.531695
0.9 0.8  200       107 2025-07-29 2026-05-14 629.916870  748.169983 118.253113         18.772812
0.9 0.8  200       108 2025-07-30 2026-05-15 629.123657  739.169983 110.046326         17.492002

In [23]:
# --- RECONCILIATION: recompute total_return_pct and sharpe from trade_log_df for
# EVERY config with trades, and compare against the pipeline's results_df row by row.

recon_rows = []

for (q, r, tau), group in trade_log_df.groupby(["q", "r", "tau"]):
    n = len(group)
    rets = group["trade_return_pct"].values / 100.0  # back to simple-return units

    recomputed_total_return = 100 * rets.sum()
    recomputed_mean = rets.mean()
    recomputed_std = rets.std(ddof=1) if n > 1 else np.nan
    recomputed_sharpe = (
        (recomputed_mean / recomputed_std) * np.sqrt(252 / tau)
        if n > 1 and recomputed_std > 0 else np.nan
    )

    pipeline_row = results_df[
        (results_df.q == q) & (results_df.r == r) & (results_df.tau == tau)
    ].iloc[0]

    recon_rows.append({
        "q": q, "r": r, "tau": tau,
        "trades_logged": n,
        "trades_pipeline": pipeline_row["trades"],
        "total_return_logged": round(recomputed_total_return, 4),
        "total_return_pipeline": round(pipeline_row["total_return_pct"], 4),
        "sharpe_logged": round(recomputed_sharpe, 4) if not np.isnan(recomputed_sharpe) else np.nan,
        "sharpe_pipeline": round(pipeline_row["sharpe"], 4) if not np.isnan(pipeline_row["sharpe"]) else np.nan,
    })

recon_df = pd.DataFrame(recon_rows)
recon_df["trades_match"] = recon_df["trades_logged"] == recon_df["trades_pipeline"]
recon_df["return_match"] = (recon_df["total_return_logged"] - recon_df["total_return_pipeline"]).abs() < 0.01
recon_df["sharpe_match"] = (
    (recon_df["sharpe_logged"] - recon_df["sharpe_pipeline"]).abs() < 0.001
) | (recon_df["sharpe_logged"].isna() & recon_df["sharpe_pipeline"].isna())

print(recon_df.to_string(index=False))
print()
all_match = recon_df[["trades_match", "return_match", "sharpe_match"]].all().all()
print(f"ALL CONFIGS RECONCILE EXACTLY: {all_match}")

assert all_match, "Reconciliation failed -- trade log does not tally with results_df!"

  q   r  tau  trades_logged  trades_pipeline  total_return_logged  total_return_pipeline  sharpe_logged  sharpe_pipeline  trades_match  return_match  sharpe_match
0.8 0.8  200            117            117.0            1857.7831              1857.7831         4.1925           4.1925          True          True          True
0.9 0.8  100            147            147.0             622.5394               622.5394         1.7023           1.7023          True          True          True
0.9 0.8  200            108            108.0            1646.4863              1646.4863         4.6809           4.6809          True          True          True

ALL CONFIGS RECONCILE EXACTLY: True

In [24]:
# --- Save the full trade log to disk for permanent inspection alongside the notebook ---
trade_log_path = "../data/processed/SPY_2025_trade_log.csv"
trade_log_df.to_csv(trade_log_path, index=False)
print(f"Full trade log saved to: {trade_log_path}")
print(f"Rows: {len(trade_log_df)}")

Full trade log saved to: ../data/processed/SPY_2025_trade_log.csv
Rows: 372

In [25]:
results_df.sort_values("total_return_pct", ascending=False).head(10)

,q,r,tau,p_min,se_max,trades,total_return_pct,mean_trade_return_pct,std_trade_return_pct,sharpe
1,0.8,0.8,200,0.5,0.01,117,1857.783131,15.878488,4.251248,4.192548
4,0.9,0.8,200,0.5,0.01,108,1646.486292,15.245243,3.655863,4.680904
3,0.9,0.8,100,0.5,0.01,147,622.539396,4.234962,3.949298,1.702276
0,0.8,0.8,100,0.5,0.01,0,0.000000,NaN,NaN,NaN
2,0.8,0.8,300,0.5,0.01,0,0.000000,NaN,NaN,NaN
5,0.9,0.8,300,0.5,0.01,0,0.000000,NaN,NaN,NaN

In [26]:
results_df.sort_values("sharpe", ascending=False).head(10)

,q,r,tau,p_min,se_max,trades,total_return_pct,mean_trade_return_pct,std_trade_return_pct,sharpe
4,0.9,0.8,200,0.5,0.01,108,1646.486292,15.245243,3.655863,4.680904
1,0.8,0.8,200,0.5,0.01,117,1857.783131,15.878488,4.251248,4.192548
3,0.9,0.8,100,0.5,0.01,147,622.539396,4.234962,3.949298,1.702276
0,0.8,0.8,100,0.5,0.01,0,0.000000,NaN,NaN,NaN
2,0.8,0.8,300,0.5,0.01,0,0.000000,NaN,NaN,NaN
5,0.9,0.8,300,0.5,0.01,0,0.000000,NaN,NaN,NaN

In [27]:
ds.close()